apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://89.168.59.45:909
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "5s"

  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://localhost:9093
    editable: false